apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xsgn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-xsgn@sha256:de0c1cc1cadb430491f35cfbd691910cf868358993d4f2cbbdb7ae2d81f91a89
        name: my-nodejs
        resources: {}
status: {}
